[package]
name = "shamir-secret-sharing"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["rlib"]
name="shamir"

[dependencies]
rand = "0.8.5"
subtle = "2.5.0"
zeroize = "1.7.0"
hex = "0.4.3"
